public enum Occupation {
ACCOUNTANT, ARCHITECT, ARTIST, ATHLETE, 
BARBER, BARTENDER, 
CARPENTER, CHEMIST, 
DENTIST, 
ENGINEER, 
FARMER, 
LAWYER, 
MANAGER, MODEL, 
PHARMACIST, PHOTOGRAPHER, PILOT, PLUMBER, POLICEMAN, PROGRAMMER,
NURSE, 
MATHEMATICIAN, MUSICIAN, 
SOLDIER, STUDENT, SURGEON, 
TEACHER, 
}

// 4 Tiers of occupation. Tier 4 = +4, Tier 3 = +3, 