public enum Occupation {
	ACCOUNTANT, ARCHITECT, ARTIST, ATHLETE, 
	BARBER, BARTENDER, 
	CARPENTER, CHEMIST, 
	DENTIST, 
	ENGINEER, 
	FARMER, 
	LAWYER, 
	MANAGER, MODEL, 
	PHARMACIST, PHOTOGRAPHER, PILOT, PLUMBER, POLICE_OFFICER, PROGRAMMER,
	NURSE, 
	MATHEMATICIAN, MUSICIAN, 
	SOLDIER, STUDENT, SURGEON, 
	TEACHER
}